version: '2'
services:
  iftmis-postgresql:
    image: postgres:12.3
    environment:
      - POSTGRES_USER=iftmis
      - POSTGRES_PASSWORD=iftmis
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - iftmis-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
