version: '2'
services:
  iftmis-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/iftmis/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=iftmis
      - POSTGRES_PASSWORD=iftmis
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
